apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-tekton-dec10
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-tekton-dec10 
  name: go-tekton-dec10
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-tekton-dec10 
