apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-tekton-dec10-gitops
  description: This is GitOps manifest for go-tekton-dec10   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: go-tekton-dec10
    backstage.io/kubernetes-id: go-tekton-dec10 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: go-tekton-dec10   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-tekton-dec10
